name: Clone Repo 
description: 在github action 运行Clone Repo并上传至自己仓库的新分支程序
inputs:
  clone_repo_url:
    description: '需要克隆的仓库地址，不含`.git`'
    required: true
  upload_repo:
    description: '上传仓库地址'
    required: false
    default: ${{ github.repository }}
  publish_branch:
    description: 'Set a target branch for deployment. || 上传分支'
    required: false
    default: $(basename $clone_url .git)
  user_name:
    description: 'Github user name || Github 用户名'
    required: false
    default: 'github.actor'
  user_email:
    description: 'Github email || Github 邮箱地址'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  github_token:
    description: 'The deploy key for Github Pages repo || Github 上传密匙'
    required: true
  commit_msg:
    description: 'Git commit messages to your GitHub Pages repository.'
    required: false
    default: ''
  publish_dir:
    description: 'Set an input directory for deployment. || 上传目录'
    required: false
    default: './'
  custom_command:
    description: '自定义命令'
    required: false
env:
  TZ: Asia/Shanghai
runs:
  using: "composite"
  steps:
    - name: upload
      shell: bash
      run: |
        clone_url=${{ inputs.clone_repo_url }}
        git clone ${{ inputs.clone_repo_url }} repo_temp
        cd repo_temp
        ls
        git config --global user.email "${{ inputs.user_email }}"
        git config --global user.name "${{ inputs.user_name }}"
        cd ${{ inputs.publish_dir }}
        ${{ inputs.custom_command }} && rm -rf .git && git init && git remote add origin git@github.com:${{ inputs.upload_repo }}.git && git add . && git checkout -b ${{ inputs.publish_branch }} && git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')" && git push --force --quiet https://${{ inputs.user_name }}:${{ inputs.github_token }}@github.com/${{ inputs.upload_repo }} ${{ inputs.publish_branch }}:${{ inputs.publish_branch }}
 #       cd ${{ github.action_path }} && ls -a && pwd
