name: Clone Repo 
description: 在github action 运行Clone Repo并上传至自己仓库的新分支程序
inputs:
  clone_repo_url:
    description: '需要克隆的仓库地址，不含`.git`'
    required: true
  upload_repo:
    description: '上传仓库地址'
    required: true
    default: '${{ GITHUB_ACTION_REPOSITORY }}'
  user_name:
    description: 'Github user name || Github 用户名'
    required: false
    default: 'github-actions[bot]'
  user_email:
    description: 'Github email || Github 邮箱地址'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  github_token:
    description: 'The deploy key for Github Pages repo || Github 上传密匙'
    required: true
  commit_msg:
    description: 'Git commit messages to your GitHub Pages repository.'
    required: false
    default: '"GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"'
env:
  TZ: Asia/Shanghai
runs:
  using: "composite"
  steps:
    - name: upload
      shell: bash
      run: |
        git clone ${{ inputs.clone_repo_url }} repo_temp
        cd repo_temp
        ls
        CLONE_REPO_DIR=${CLONE_REPO##*/}
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        rm -rf .git && git init && git remote add origin git@github.com:${{ inputs.upload_repo }}.git && git add . && git checkout -b ${{ CLONE_REPO_DIR }} && git commit -m "GitHub Actions Auto Upload" && git push --force --quiet https://${{ inputs.user_name }}:${{ inputs.github_token }}@github.com/${{ inputs.upload_repo }} ${{ CLONE_REPO_DIR }}:${{ CLONE_REPO_DIR }}
 #       cd ${{ github.action_path }} && ls -a && pwd
