name: Clone Repo 
description: 在github action 运行Clone Repo并上传至自己仓库的新分支程序
inputs:
  clone_repo_url:
    description: '需要克隆的仓库地址，不含`.git`'
    required: true
  github_upload_repo:
    description: '上传仓库地址'
    required: false
    default: ${{ github.repository }}
  gitee_upload_repo:
    description: '上传至gitee仓库地址'
    required: false
  gitee_user_name:
    description: 'Gitee user name || Gitee 用户名'
    required: false
  gitee_user_email:
    description: 'Gitee email || Gitee 邮箱地址'
    required: false
  gitee_token:
    description: 'The deploy key for Gitee repo || Gitee 上传密匙'
    required: false
    default: ''
  publish_branch:
    description: 'Set a target branch for deployment. || 上传分支'
    required: false
    default: $(basename $clone_url .git)
  github_user_name:
    description: 'Github user name || Github 用户名'
    required: false
    default: 'github.actor'
  github_user_email:
    description: 'Github email || Github 邮箱地址'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  github_token:
    description: 'The deploy key for Github Pages repo || Github 上传密匙'
    required: false
    default: ''
  commit_msg:
    description: 'Git commit messages to your GitHub Pages repository.'
    required: false
    default: ''
  publish_dir:
    description: 'Set an input directory for deployment. || 上传目录'
    required: false
    default: './'
  custom_command:
    description: '自定义命令'
    required: false
env:
  TZ: Asia/Shanghai
runs:
  using: "composite"
  steps:
    - name: Clone Repo
      shell: bash
      run: |
        dir_temp=repo_temp
        clone_url=${{ inputs.clone_repo_url }}
        git clone ${{ inputs.clone_repo_url }} $dir_temp
        git config --global user.email "${{ inputs.github_user_email }}"
        git config --global user.name "${{ inputs.github_user_name }}"
    - name: Sync to Github
      if: [ ${{ inputs.github_token }} != ''}} ]
      shell: bash
      run: |
        cd repo_temp && pwd
        cd ${{ inputs.publish_dir }}
        ${{ inputs.custom_command }} && rm -rf .git && git init && git remote add origin git@github.com:${{ inputs.github_upload_repo }}.git && git add . && git checkout -b ${{ inputs.publish_branch }} && git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')" && git push --force --quiet https://${{ inputs.github_user_name }}:${{ inputs.github_token }}@github.com/${{ inputs.github_upload_repo }} ${{ inputs.publish_branch }}:${{ inputs.publish_branch }}
        pwd && ls -a
    - name: Sync to Gitee
      if: ${{ inputs.gitee_token }} != ""
      shell: bash
      run: |
        mirror() {
          pwd && ls -a
          cd "repo_temp"
          ${{ inputs.custom_command }} && rm -rf .git && git init && git remote add gitee git@gitee.com:$4.git
          git checkout -b $5
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet https://$2:$3@gitee.com/$4 $5:$5
          cd ..
          }
          mirror $dir_temp ${{ inputs.gitee_user_name }} ${{ inputs.gitee_token }} ${{ inputs.gitee_upload_repo }} ${{ inputs.publish_branch }}
  #       cd ${{ github.action_path }} && ls -a && pwd
